openapi: 3.1.0

info:
  title: Contacts API
  version: 1.0.0
  description: API для керування контактами.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://nodejs-hw-mongodb-3z6d.onrender.com
    description: Production server
  - url: http://localhost:3000
    description: Local server
    x-internal: true

paths:
  /contacts:
    get:
      tags:
        - Contacts
      summary: Get list of contacts
      operationId: getContacts
      description: Get list of contacts with this endpoint
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Page number for pagination (default: 1)
          required: false
          schema:
            type: integer
            minimum: 1
            example: 1
        - name: perPage
          in: query
          description: Number of items per page (default: 10)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            example: 10
        - name: sortBy
          in: query
          description: Field name to sort by (default: _id)
          required: false
          schema:
            type: string
            example: name
        - name: sortOrder
          in: query
          description: Sort order direction
          required: false
          schema:
            type: string
            enum: [asc, desc]
            example: asc
        - name: isFavourite
          in: query
          description: Show contacts with favourite status only
          required: false
          schema:
            type: boolean
            example: true
        - name: contactType
          in: query
          description: Type of the contact (default: personal)
          required: false
          schema:
            type: string
            enum: ['work', 'home', 'personal']
            example: personal
      responses:
        '200':
          description: Successful response with contacts list
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
                  page:
                    type: integer
                    example: 1
                  perPage:
                    type: integer
                    example: 10
                  total:
                    type: integer
                    example: 100
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Contact:
      type: object
      properties:
        id:
          type: string
          example: "60d0fe4f5311236168a109ca"
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          example: "john.doe@example.com"
        phone:
          type: string
          example: "+123456789"
        favorite:
          type: boolean
          example: false
        contactType:
          type: string
          enum: ['work', 'home', 'personal']
          example: personal

  responses:
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized access

    NotFoundError:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Not found