openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations with contacts.
servers:
  - url: http://127.0.0.1:3000/api-docs
  - url: https://nodejs-hw-mongodb-3z6d.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/by-id/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/by-id/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/by-id/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
